from colorama import Fore, Back, Style

GAME_ID_LEN = 6

RESET_CURSOR = "\033[0;0H"
CLEAR = "\033[2J"

SCREEN_WIDTH = 100
SCREEN_HEIGHT = 30

BG_CHAR = ' '
BORDER_CHAR = '#'

TIME_BW_FRAMES = 0.2

HEALTH_RANGE = [30, 60]
OBJECT_COLOUR = [Fore.RED, Fore.YELLOW]

# Game object properties
KING_HEIGHT = 1
KING_WIDTH = 1
KING_POS_X = 10
KING_POS_Y = 10
KING_MAX_HEALTH = 100
KING_DAMAGE = 5
KING_ATTACK_AOE = 4

BARB_HEIGHT = 1
BARB_WIDTH = 1
BARB_MAX_HEALTH = 50
BARB_DAMAGE = 2
SPAWN_POINTS = [[5, 50], [25, 50], [15, 70]]
MARK_SPAWN = ['1', '2', '3']
TROOP_SIZE = 1
BARB_ATTACK_TIMESTEP = 0.5

TOWNHALL_HEIGHT = 3
TOWNHALL_WIDTH = 4
TOWNHALL_POS_X = int((SCREEN_HEIGHT - TOWNHALL_HEIGHT) / 2)
TOWNHALL_POS_Y = int((SCREEN_WIDTH - TOWNHALL_WIDTH) / 2)
TOWNHALL_HITPOINTS = 60

HUT_HEIGHT = 2
HUT_WIDTH = 2
HUT_POS = [[10, 13], [20, 50], [22, 14], [15, 90], [4, 66]]
HUT_HITPOINTS = 40

WALL_HITPOINTS = 20
WALL_POS = []
WALL_LEFT, WALL_RIGHT = 40, 59
WALL_TOP, WALL_BOTTOM = 10, 18
for x in range(WALL_TOP, WALL_BOTTOM+1):
    WALL_POS.append([x, WALL_LEFT])
    WALL_POS.append([x, WALL_RIGHT])
for y in range(WALL_LEFT+1, WALL_RIGHT):
    WALL_POS.append([WALL_TOP, y])
    WALL_POS.append([WALL_BOTTOM, y])

CANNON_HEIGHT = 1
CANNON_WIDTH = 1
CANNON_DAMAGE = 5
CANNON_RANGE = 10
CANNON_COOL_OFF = 0.5
CANNON_POS = [[14, 55], [10, 70], [14, 30]]

